name: flutter_provider_utilities
description: A set of utilities for provider package.
version: 1.0.2
homepage: https://www.quantos.it

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  tuple: ^2.0.0-nullsafety.0  

dev_dependencies:
  flutter_test:
    sdk: flutter