name: flutter_provider_utilities
description: A set of utilities for provider package.
version: 0.0.3
homepage: https://www.quantos.it

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter